### ISSUE TITLE
crashes while running test

### ISSUE THREAD

**Issue by BluMist** [ypresto/AutoLayoutLint#7]
I only imported AutoLayoutLint into the solution with cocoapods, but it is already crashing.

Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<RandomView 0x7f86acd60c40> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key containerView.'

The view in question is a UICollectionViewCell

**Comment by ypresto** [comment]
> this class is not key value coding-compliant for the key containerView

This library does not do anything on the key `containerView`.
It seems you have dangling outlet (without IBOutlet code) which is remained in xib.

**Comment by BluMist** [comment]
awesome, found the dangling outlet.
